### ISSUE TITLE
Game Crash

### ISSUE THREAD

**Issue by THB0705** [Ben-Ryder/Conqueror-of-Empires#3]
After I select which players I want to play with and click start game, my game crashes. I am on Windows.

`root - ERROR - caught at main
Traceback (most recent call last):
  File "main.py", line 16, in <module>
  File "main.py", line 12, in main
  File "project\control\controller.py", line 38, in run
  File "project\control\controller.py", line 61, in run_newgame
  File "project\menus\newgame.py", line 82, in __init__
  File "project\menus\newgame.py", line 86, in run
  File "project\menus\newgame.py", line 150, in handle_events
  File "project\menus\newgame.py", line 96, in create_game
  File "project\game\new.py", line 11, in make
  File "project\data.py", line 9, in save
FileNotFoundError: [Errno 2] No such file or directory: '\\Conqueror-of-Empires-master\\Windows\\Conqueror-of-Empires-v1.0\\data\\\\saved\\hi'`

I called the game "hi" for testing purposes by the way.

**Comment by ben-ryder** [comment]
Hi, after re-downloading myself I got the same issue. It should be fixed by adding a `saved` folder within the `data` folder, for some reason it hadn't been included when I built. 
I'll also make the the fix and apply it here of course. (and maybe for the future, edit so it can create the folder if none present).
Let me know if that has solved the issue for you too, Thanks :)

**Comment by THB0705** [comment]
That fixes the problem!
